import { Inter } from "next/font/google";
import "./globals.scss";
import { NextUIProviders } from "./Providers/NextUIProvider";
import Header from "./Components/Header";
import Footer from "./Components/Footer";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextUIProviders>
          <Header />

          {children}
          <Footer/>
        </NextUIProviders>
      </body>
    </html>
  );
}
